# This file is created by-Honey (not automatically generated by django)

from django.http import HttpResponse
from django.shortcuts import render


# Home page
def index(request):
    return render(request, "index.html")


# Analyze text
def analyze(request):
    djtext = request.POST.get('text', 'default')
    removpunc = request.POST.get('removepunc', 'off')
    upperCase = request.POST.get('upperCase', 'off')
    extraSpaceRemover = request.POST.get('extraSpaceRemover', 'off')
    newLineRemover = request.POST.get('newLineRemover', 'off')
    charCount = request.POST.get('charCount', 'off')

    analyzedText = ""
    purpose = ""

    # Checking which option /checkbox user has ticked
    if removpunc == 'on':

        punctuationList = '''!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~'''

        for char in djtext:

            if char == '\n':
                analyzedText += '\n'
            elif char not in punctuationList:
                analyzedText = analyzedText + char

        purpose += 'Removing Punctuation '

    if (upperCase == 'on'):

        if analyzedText != "":
            djtext = analyzedText
            analyzedText = ""

        for ch in djtext:
            analyzedText = analyzedText + ch.upper()

        purpose += 'Capatalize all '

    if (extraSpaceRemover == 'on'):

        if analyzedText != "":
            djtext = analyzedText
            analyzedText = ""

        for i in range(len(djtext)):
            if (djtext[i] == ' ' and djtext[i + 1] == ' '):
                pass
            else:
                analyzedText = analyzedText + djtext[i]
        purpose += 'Removing Extra Space '

    if (newLineRemover == 'on'):

        if analyzedText != "":
            djtext = analyzedText
            analyzedText = ""

        for ch in djtext:
            if ch != "\n" and ch != '\r':
                analyzedText = analyzedText + ch

        purpose += 'New Line Removing '

    if (charCount == 'on'):
        count = 0
        djtext = djtext.replace(' ', '')
        djtext = djtext.replace('\r\n', '')

        count = len(djtext)

        count = str(count)

        purpose += 'Character count'
        analyzedText += " count of characters=" + str(count)

    if (
            removpunc == 'off' and upperCase == 'off' and extraSpaceRemover == 'off' and newLineRemover == 'off' and charCount == 'off'):
        return HttpResponse("Error:Text String Empty!!")

    params = {'purpose': purpose, 'analyzed_text': analyzedText}
    return render(request, "analyze.html", params)


def AboutUs(request):
    return render(request, "AboutUs.html")


def Contact(request):
    return render(request, "Contact.html")
